version: "3"
services:

  development:
    image: "ovgudrivingswarm/development:latest"
    build:
      context: "."
      dockerfile: "development.Dockerfile"
    ports: ["127.0.0.1:1800:1800", "127.0.0.1:1900:1900", "127.0.0.1:5900:5900"]
    hostname: "ros-development"
    volumes:
    - "./workspace:/home/docker/workspace"
    - "./ssh:/home/docker/.ssh"
    devices:
    - "/dev/dri:/dev/dri:rw"

  turtlebot:
    image: "ovgudrivingswarm/turtlebot:latest"
    build:
      context: "."
      dockerfile: "turtlebot.Dockerfile"

    # TODO: Gazebo UI (Maybe with SSH-based X11 forwarding?! Something that doesn't require a DE...)
    environment:
      ROBOTS: 6
    devices:
    - "/dev/dri:/dev/dri"

  turtleslim:
    image: "ovgudrivingswarm/turtlebot:slim"
    build:
      context: "."
      dockerfile: "turtleslim.Dockerfile"
    devices:
    - "/dev/dri:/dev/dri"

  deploy:
    image: "ovgudrivingswarm/base:deploy"
    build:
      context: "."
      dockerfile: "deploy.Dockerfile"
    volumes:
    - "./deployspace:/home/docker/workspace"
    devices:
    - "/dev/dri:/dev/dri"

  base:
    image: "ovgudrivingswarm/base:latest"
    build:
      context: "."
      dockerfile: "base.Dockerfile"
    devices:
    - "/dev/dri:/dev/dri"

    # TODO: driving_swarm_infrastructure
    # TODO: turtlebot3 dependencies:
    # - https://github.com/ROBOTIS-GIT/turtlebot3/blob/ros2/turtlebot3.repos
    # - https://emanual.robotis.com/docs/en/platform/turtlebot3/ros2_setup/#pc-setup

